### ISSUE TITLE
Add support for point-to-multipoint forwarders in NSM

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1094]
## Requires

1. https://github.com/networkservicemesh/sdk/pull/1084
2. https://github.com/networkservicemesh/sdk/pull/1083

## Overview

See at  https://docs.google.com/presentation/d/1b_jtSFygaYPQa6Xd0pRR50enieaydu6yK8fxprp7bno/edit?usp=sharing

## Link to the Google Docs document

See at https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=D2ctnZZM9BhLXnHZu3kN&title=Forwarder%20as%20NSE.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D14HHm-3sY1Zkl3jkV4CRgDNhIgMvNTTkU%26export%3Ddownload

## Tasks

- [x]  1. Remove loop `nsc->nsmgr->forwarder->nmsgr->nse` to `nsc->nsmgr->forwarder->nse`. 
Total estimation: `4.3d`

- [x] 1.1. Update discover chain element for nsmgr and forwarder and test forwarder selection (interpose could be removed).
Estimation: `0.8d`

- [x] 1.2. Add support `Find` for `interpose` RegistryServer.
Estimation: `0.5d`

- [x] 1.3. Update `filtermechanisms` for forwarders .
Estimation: `1d`

- [ ] 1.4 Rework a few unit tests with the new architecture and add new ones to cover p.1 (i.e. add examples on `nsc->nsmgr->forwarder->nse1...nseN`).
Estimation: `2d`

- [ ] 2. Update dependent repositories (i.e. update forwarders).
Estimation: `0.5d`

- [ ] 3.  Add an example on forwarder selection by capabilities(labels).
Estimation: `0.5d`

- [ ] 4. Verify that each integration test is stable with the new architecture.
Estimation: `3d`

Total Estimation: `8.3d`

**Comment by denis-tingaikin** [comment]
@edwarnicke Question on 4. 

How should forwarders provide their labels?

Currently, I see two options:
1. Just pass labels into env config for each forwarder and use it on registartion
2. Cluster admin should register cross-NSE such as it does for NSE.
3. Your option.


For me option 1. is looking good.

**Comment by denis-tingaikin** [comment]
@ljkiraly Am I get correctly that you are started to work on p2mp in https://github.com/networkservicemesh/sdk/pull/1093?

**Comment by ljkiraly** [comment]
@denis-tingaikin No, that is related to [cmd-forwarder-vpp#358](https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/358) 
It was a  poor choice of naming for an IPAM - that's why I renamed it.
Sorry for confusion.

**Comment by denis-tingaikin** [comment]
@ljkiraly all fine :) 

Is this one https://github.com/networkservicemesh/sdk/pull/1093 is required for p2mp?

**Comment by denis-tingaikin** [comment]
@ljkiraly Got it thanks!

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm with you on option 1:

> Just pass labels into env config for each forwarder and use it on registartion
