### ISSUE TITLE
Exclude prefixes already in use in a POD by other Network Services

### ISSUE THREAD

**Issue by Sol-0** [networkservicemesh/sdk#1188]
Overview
---
Feature description can be found here: https://github.com/networkservicemesh/sdk/issues/1188#issuecomment-987075919

**Comment by Sol-0** [comment]
Hi @edwarnicke ,
This feature is planned for the next release.

Could you please share some use-cases for this feature so that we could understand the scope better and plan accordingly?

**Comment by denis-tingaikin** [comment]
We've got a bit discussed this with @edwarnicke internally. 

There is a short summary:

## Description

Essentially, if ExP1 is the exclude prefixes we get from the cluster and the NSC asks first for ns1, then NSE-1 gets ExP1 for its excluded prefixes, and returns a set of IP addresses and routes that forms ExP-NS1.  When the NSC goes to request ns-2 it sends (ExP1 ∪ ExP-NS1) as the Exclude prefixes to NSE-2.  


## References

https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/connectioncontext.proto#L60

## Use-case

1. nsc requests "ns1" and "ns2"
2. endpoint1 for "ns1" extracts prefixes and mark them as excluded for request
3. endpoint2 for "ns2" extracts prefixes and mark them as excluded for request

Expected: endpoint2 should exclude prefixes from endpoint1
Actual: ?

## Sub-tasks:

- [ ] Check that excludes mechanics is working by modifying the NSC.
- [ ] Add chain client element or wrapper client element for SDK i(if step 1 is good).
- [ ] Add the element from step2 into all clients.
- [ ] Add an example in deployments-k8s.

**Comment by Sol-0** [comment]
Update:

I and @denis-tingaikin have implemented a small proof-of-concept (modified NSC code) and checked that exclusion mechanism is working fine (the 1st sub-task in https://github.com/networkservicemesh/sdk/issues/1188#issuecomment-987075919):
- IP addresses for 2 endpoints are correctly assigned in NSC
- pings are working fine either in case NSC -> endpoints and in case endpoints -> NSC

I'm going to implement a chain element having the same functionality.

**Comment by edwarnicke** [comment]
@denis-tingaikin I'm confused by this:
> 1. nsc requests "ns1" and "ns2"
> 2. endpoint1 for "ns1" extracts prefixes and mark them as excluded for request
> 3. endpoint2 for "ns2" extracts prefixes and mark them as excluded for request
> Expected: endpoint2 should exclude prefixes from endpoint1
> Actual: ?

This doesn't seem to mention the role of NSCs in adding exclude prefixes (as mentioned in the description).  It's also not clear to me what entity *enforces* that we respect excluded prefixes.  Clearly the endpoints should try to... but if they fail (or are buggy) then what enforces exclude prefixes?
