### ISSUE TITLE
Fix leaks in 'trace' element

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1635]
https://github.com/networkservicemesh/sdk/commit/15fe129fec59610b4da3b4887f2d7b29d4705d9f

## Steps to reproduce

It's actual for metrics and for logger spans (when otel is disabled)

1. Run https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/observability/jaeger_and_prometheus 
2. Continus scale client/endpoint
3. Check mem profiles

Actual: Memory leaks.
Expected: No memory leaks.

**Action plan**: (provided by @VitalyGushin )
- [x] Analysis of existing profiles from the community
- [x] Scaling test rc1
- [x] Scaling test rc1 + tracing enabled, compare results
- [x] Code research (TELEMETRY=false scenario) 7h
- [x] Prepare fixes and execute scaling test for logrus/opa/recvfd components 14h
- [x] Prepare builds for scaling test rc3 + tracing enabled, test/result analysis 3h
- [x] Identifying memory leaking methods in profiles 3h
- [x] Provide testing/analytics for the TELEMETRY=true scenario 4h
- [ ] Prepare fixes and check them with benchmark tests 14h
- [ ] Prepare images, perform the scaling test with profiling, results analysis 4h
- [ ] Prepare PR (in case of a successful result in the profile), review fixes 3h

**Comment by denis-tingaikin** [comment]
@VitalyGushin profiles:

[forwarder-vpp_memprofiles_20240519135433.tar (1).gz](https://github.com/networkservicemesh/sdk/files/15469802/forwarder-vpp_memprofiles_20240519135433.tar.1.gz)
[nsmgr_memprofiles_20240519135233.tar (1).gz](https://github.com/networkservicemesh/sdk/files/15469803/nsmgr_memprofiles_20240519135233.tar.1.gz)

**Comment by denis-tingaikin** [comment]
Finally, we've found a root cause with the trace element, and it will be considered in the separate issue https://github.com/networkservicemesh/sdk/issues/1667
