### ISSUE TITLE
NSE Composition

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#872]
- [x] Decomposition (https://github.com/networkservicemesh/sdk/issues/820).
- [x] Sandbox tests (https://github.com/networkservicemesh/sdk/issues/880).
- [x] Migrate ACL from monorepo (networkservicemesh/sdk-vpp#213).
- [ ] Create firewall application (https://github.com/networkservicemesh/sdk/issues/952).
- [ ] MD integration tests (https://github.com/networkservicemesh/deployments-k8s/issues/1014).

**Comment by denis-tingaikin** [comment]
I think this is useful to have core issue that have context for all sub issues :)
